### ISSUE TITLE
Is this repo obsolete?

### ISSUE THREAD

**Issue by Kostr** [amd/amd_hsmp#2]
What is the difference of this repo and the https://github.com/AMDESE/amd_hsmp ?
It looks like the last one has active development opposed to this one.

**Comment by nchatrad** [comment]
Hi Kostr, apologies for delayed response. To make the driver scalable and maintainable we have modified the interface, updated driver is submitted for upstream review https://www.spinics.net/lists/platform-driver-x86/msg30726.html
a copy of the same is uploaded https://github.com/amd/amd_hsmp
